### ISSUE TITLE
Monster object has no attribute

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#103]
Monster: Hired Goon moveTilesLeft: 3
Monster: Hired Goon moveTilesLeft: 2
Monster: Hired Goon moveTilesLeft: 1
No more choices found for: Hired Goon
Blue Ghost is using ability: Cloud Vision on Guy Threepwood
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\server.py", l
ine 25, in server_loop
    self.CS.handle(port, command)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\servercombat.
py", line 60, in handle
    self.check_turn_end(self.server.person[command.id].cPane)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\servercombat.
py", line 261, in check_turn_end
    self.end_turn(combatPane)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\servercombat.
py", line 269, in end_turn
    self.monster_phase(combatPane)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\servercombat.
py", line 296, in monster_phase
    message = mon.performAction(self.server, combatPane)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\monster.py",
line 234, in performAction
    abil.use(target)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\spell.py", li
ne 61, in use
    spellSuccess = Dice.rollSuccess(100 - self.owner.statusSpellFailureChance)
  File "D:\Kyle\Documents!Documents\Programming\GitHub\akintu\src\person.py", l
ine 263, in statusSpellFailureChance
    return self._statusSpellFailureChance
exceptions.AttributeError: 'Monster' object has no attribute '_statusSpellFailur
eChance'

**Comment by BlackVegetable** [comment]
Fixed.
