### ISSUE TITLE
No combat outside of pane 0,0

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#104]
Combat fails due to "server errors" when entered outside of pane 0,0.

**Comment by jabelch** [comment]
Here's a console print from when I encountered this issue.

Loading pane (-1, 1)
Loading pane ((-1, 1), (23, 5), 2)
Server error: Attempted to stop non-existent ai function: RUN
Unloading pane ((-1, 1), (23, 5), 2)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ai.py", line 29, in wander
    while not newloc in region or not self.server.tile_is_open(newloc):
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 152, in tile_
is_open
    for i in self.pane[location.pane].person]
exceptions.KeyError: 61772144
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 67, in server
_loop
    if p != port and command.location.pane == self.person[i].location.pane and \

exceptions.KeyError: 61772144
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ai.py", line 29, in wander
    while not newloc in region or not self.server.tile_is_open(newloc):
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 152, in tile_
is_open
    for i in self.pane[location.pane].person]
exceptions.KeyError: 61772144
ClientData lost connection.
ClientDataFactory lost connection.
ServerData lost connection to client on 11023.

**Comment by BlackVegetable** [comment]
Reminder from yesterday, this happens not just outside of pane 0,0.  It instead seems to be permanently triggered after any pane switching is performed.  Hopefully that gives you a place to start looking.
