### ISSUE TITLE
Monster/Player combat bug - Rookie Gladiator

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#109]
Looks like an issue with gear and hands.  I'll let you take a look at it Devin.

Loading pane (0, 0)
Loading pane ((0, 0), (1, 10), 6)
Server error: Attempted to stop non-existent ai function: RUN
No more choices found for: Rookie Gladiator
~~END MONSTER PHASE~~.
Selection mode enabled
Mysterious Adventurer
Rookie Gladiator
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 25, in server
_loop
    self.CS.handle(port, command)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 68, in
handle
    abil.use(target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 84, in use
    self.action(self, target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 93, in _basi
cAttack
    hit = Combat.calcHit(source, target, "Physical")
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 291, in calcH
it
    if source.team == "Players" and source.usingWeaponStyle("Dual"):
  File "e:\Users\Josh\Documents\GitHub\akintu\src\person.py", line 2523, in usin
gWeaponStyle
    return (handOne is not None and handTwo is not None and not self.usingShield
("Any"))
  File "e:\Users\Josh\Documents\GitHub\akintu\src\person.py", line 2488, in usin
gShield
    shield = self.equippedItems.equippedShield
  File "e:\Users\Josh\Documents\GitHub\akintu\src\equippeditems.py", line 152, i
n equippedShield
    if( self._allGear['Off Hand'].isinstance(equipment.Armor) ):
exceptions.AttributeError: 'Armor' object has no attribute 'isinstance'
ClientData lost connection.
ClientDataFactory lost connection.
ServerData lost connection to client on 16305.

**Comment by jabelch** [comment]
BTW, I closed the connection, that isn't part of the issue.

**Comment by BlackVegetable** [comment]
Done
