### ISSUE TITLE
In Combat - Monster attack breaks when attempting to hash a list

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#111]
Loading pane (0, 0)
Loading pane ((0, 0), (6, 9), 8)
Server error: Attempted to stop non-existent ai function: RUN
Selection mode enabled
Mysterious Adventurer
Common Thug
Hired Goon
No more choices found for: Hired Goon
No more choices found for: Common Thug
~~END MONSTER PHASE~~.
~~END MONSTER PHASE~~.
~~END MONSTER PHASE~~.
~~END MONSTER PHASE~~.
Hired Goon is using ability: Melee Attack on Mysterious Adventurer
Normal Hit
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 25, in server
_loop
    self.CS.handle(port, command)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 60, in
handle
    self.check_turn_end(self.server.person[command.id].cPane)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 275, in
 check_turn_end
    self.end_turn(combatPane)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 283, in
 end_turn
    self.monster_phase(combatPane)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 310, in
 monster_phase
    message = mon.performAction(self.server, combatPane)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\monster.py", line 234, in perf
ormAction
    abil.use(target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 84, in use
    self.action(self, target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 94, in _basi
cAttack
    Combat.basicAttack(source, target, hit)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 597, in basic
Attack
    Combat.monsterAttack(source, target, hitType[0], **params)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 624, in monst
erAttack
    color='red', character=target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 85, in sendCo
mbatMessage
    Combat.gameServer.SDF.send(port, messageObj)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\network.py", line 56, in send
    if port in self.clients:
exceptions.TypeError: unhashable type: 'list'

**Comment by BlackVegetable** [comment]
Fixed
