### ISSUE TITLE
OnHitEffect instance as first argument

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#112]
Loading pane (0, 0)
Loading pane ((0, 0), (18, 13), 2)
Server error: Attempted to stop non-existent ai function: RUN
No more choices found for: Hired Goon
No more choices found for: Hired Goon
~~END MONSTER PHASE~~.
Selection mode enabled
Mysterious Adventurer
Hired Goon
Normal Hit
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 25, in server
_loop
    self.CS.handle(port, command)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 68, in
handle
    abil.use(target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 84, in use
    self.action(self, target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 94, in _basi
cAttack
    Combat.basicAttack(source, target, hit)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 595, in basic
Attack
    Combat.weaponAttack(source, target, hitType[0], **params)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 679, in weapo
nAttack
    elementalEffects = Combat.applyOnHitEffects(source, target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\combat.py", line 709, in apply
OnHitEffects
    result = effect.apply(source, target)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\onhiteffect.py", line 19, in a
pply
    self.function(self.count, source, target)
exceptions.TypeError: unbound method applyElementalDamage() must be called with
OnHitEffect instance as first argument (got int instance instead)

**Comment by BlackVegetable** [comment]
Fixed... I think.  I'll push this and only more onhiteffect weapons will be able to test it (weapons have a small chance of being generated with such.)
