### ISSUE TITLE
Multiplayer combat when client closes connection, server breaks

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#113]
Here is my console print.  I was connected to myself, entered combat (as client), did some stuff then closed my connection.  The server broke at that point, all the monsters stopped moving.

1337 None {'seed': 'a'} ('jabelch', 'Elf', 'Assassin')
Listening for clients...
Connecting to server...
Connection made with client on port #17425
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Connection made with client on port #17430
Loading pane ((0, 0), (17, 14), 2)
Server error: Attempted to stop non-existent ai function: RUN
No more choices found for: Common Thug
~~END MONSTER PHASE~~.
Normal Hit
No more choices found for: Vile Apprentice
Common Thug is using ability: Smash on Client
Normal Hit
No more choices found for: Common Thug
~~END MONSTER PHASE~~.
Miss
Miss
Miss
Miss
Vile Apprentice is using ability: Singe on Client
Fully Resisted
No more choices found for: Vile Apprentice
Common Thug is using ability: Melee Attack on Client
Normal Hit
Common Thug is using ability: Melee Attack on Client
Normal Hit
No more choices found for: Common Thug
~~END MONSTER PHASE~~.
Miss
Normal Hit
Vile Apprentice is using ability: Singe on Client
Fully Resisted
Vile Apprentice is using ability: Singe on Client
Fully Resisted
No more choices found for: Vile Apprentice
Common Thug is using ability: Smash on Client
Normal Hit
~~END MONSTER PHASE~~.
Miss
Miss
ServerData lost connection to client on 17430.  Reason: Connection was closed cl
eanly.
Unloading pane ((0, 0), (17, 14), 2)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 134, in serve
r_loop
    self.unload_panes()
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 187, in unloa
d_panes
    self.person[i].ai.shutdown()
exceptions.KeyError: 59519152
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 34, in main
    game = Game(port=port, serverip=ip, state=state, player=player)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 84, in **init**

```
reactor.run()
```

  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 273, in
 check_turn_end
    self.combatStates[combatPane].turnTimer.cancel()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 90, in can
cel
    raise error.AlreadyCalled
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.

**Comment by BlackVegetable** [comment]
Part of this issue can probably be dealt with better once we have player death finished.  From the server's perspective, it will likely be handled much like a player dying.

**Comment by malikoth** [comment]
I think this was resolved the other day.  If not, just reopen it.  Thanks!
