### ISSUE TITLE
HealTarget Error

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#114]
~~END MONSTER PHASE~~.
Ranged Backstab AP COST: 10
Chain Grasp AP COST: 6
Hidden Shot AP COST: 5
Ranged Attack AP COST: 5
Miss
Normal Hit
Critical Hit
Normal Hit
Rookie Gladiator is using ability: Melee Attack on Flagrant Noob
Normal Hit
Rookie Gladiator is using ability: Quaff Potion on Rookie Gladiator
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 25, in server
_loop
    self.CS.handle(port, command)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 77, in
handle
    self.check_turn_end(self.server.person[command.id].cPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 276, in
 check_turn_end
    self.end_turn(combatPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 284, in
 end_turn
    self.monster_phase(combatPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 311, in
 monster_phase
    message = mon.performAction(self.server, combatPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\monster.py", line 233, in perf
ormAction
    abil.use(target)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 84, in use
    self.action(self, target)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\ability.py", line 994, in _qua
ffPotion
    Combat.healTarget(source, amountToHeal)
exceptions.TypeError: healTarget() takes exactly 3 arguments (2 given)

**Comment by BlackVegetable** [comment]
Fixed.  (I'll push the fix soon.)
