### ISSUE TITLE
Monster removal...

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#129]
$ python akintu.py
1337 None {'seed': 'ewfd'} ('Mysterious Adventurer', 'Human', 'Assassin')
Listening for clients...
Connecting to server...
Connection made with client on port #3592
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane ((0, 0), (21, 5), 4)
Server error: Attempted to stop non-existent ai function: RUN
Poisoned
Mysterious Adventurer has status enabled: Stealth
Mysterious Adventurer has status: Poison Fang T=1
Mysterious Adventurer has status enabled: Stealth
Mysterious Adventurer has status enabled: Stealth
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 128, in
server_loop
    self.pane[self.person[command.id].location.pane].person.remove(command.id)
exceptions.KeyError: 81693712

Upon killing three targets (one enemy and I remained.)
(That was in pane 0,0 with no pane switching so those issues aren't related.)

**Comment by malikoth** [comment]
I think I fixed it.  Let me know if you see it again
