### ISSUE TITLE
Combat Stealth Selection Error - Pane (-1,-1)

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#138]
Tried to use assassin stealth with the monster selected and got the following error:

Loading pane ((-1, -1), (0, 8), 4)
Server error: Attempted to stop non-existent ai function: RUN
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 25, in server
_loop
    self.CS.handle(port, command)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 85, in
handle
    source = activePlayer
exceptions.UnboundLocalError: local variable 'activePlayer' referenced before as
signment
ClientData lost connection.
ClientDataFactory lost connection.
ServerData lost connection to client on 21430.

**Comment by jabelch** [comment]
Seems to happen even with myself selected

**Comment by BlackVegetable** [comment]
Was this fixed last night?
