### ISSUE TITLE
Multiplayer chests don't work

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#139]
Found chest on tile (17, 2)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 161, in serve
r_loop
    itemList = inventories[thisPlayer]
exceptions.KeyError: <playercharacter.PlayerCharacter object at 0x039572D0>

**Comment by jabelch** [comment]
Mostly implemented.  Still not loading state (so chests do come back when the server unloads its panes). But this issue is worked out.
