### ISSUE TITLE
Game failure when entering combat on pane switch?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#144]
When you enter combat during a move that takes you across a pane, the game either crashes with a key error at line 63 in server.py or has a "deadzone" effect but the game keeps running.

@jabelch may need to be invovled as well.

**Comment by BlackVegetable** [comment]
Does not seem to be consistent... hmm... more testing will be needed.

**Comment by BlackVegetable** [comment]
Loading pane (1, -1)
Loading pane ((1, -1), (0, 4), 2)
Server error: Attempted to stop non-existent ai function: RUN
Mysterious Adventurer has status: Mystic Shield T=4
Mysterious Adventurer has status: Mystic Shield T=3
Mysterious Adventurer has status: Mystic Shield T=2
Mysterious Adventurer has status: Mystic Shield T=1
Mysterious Adventurer has status: Bleeding T=3
Mysterious Adventurer has status: Bleeding T=2
Mysterious Adventurer has status: Bleeding T=1
Mysterious Adventurer has status: Haunt T=3
Mysterious Adventurer has status: Haunt T=2
Mysterious Adventurer has status: Mystic Shield T=4
Mysterious Adventurer has status: Haunt T=1
Mysterious Adventurer has status: Mystic Shield T=3
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 29, in s
erver_loop
    self.CS.handle(port, command)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 49
, in handle
    self.update_dead_people(self.server.person[command.id].cPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 16
4, in update_dead_people
    self.victory_phase(livingPlayers, combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 35
6, in victory_phase
    self.server.SDF.queue.put((None, Command("PERSON", "REMOVE", id=monsterLeade
r.id)))
exceptions.AttributeError: 'NoneType' object has no attribute 'id'

**Comment by BlackVegetable** [comment]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 31, in s
erver_loop
    self.CS.handle(port, command)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 52
, in handle
    self.update_dead_people(self.server.person[command.id].cPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 22
3, in update_dead_people
    self.victory_phase(livingPlayers, combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 43
0, in victory_phase
    self.server.SDF.queue.put((None, Command("PERSON", "REMOVE", id=monsterLeade
r.id)))
exceptions.AttributeError: 'NoneType' object has no attribute 'id'

This happened when I killed the monster leader last.  Perhaps that will help you?  We need to figure this out before release.

**Comment by malikoth** [comment]
Maybe you can help me think through what would cause this.  When it says NoneType object has no attribute id, it means that monsterLeader.id doesn't work because monsterLeader is None, not a Person object.  server.get_monster_leader only returns None when the character you pass into it has no cPane attribute.  So the list livingPlayers that is passed in to victory_phase contains a Person who is no longer in combat.  Can you think of how a player's cPane could be set to None?

**Comment by malikoth** [comment]
I can't answer the last question I posed, but I was only asking for a person to be passed to get_monster_leader so that I could determine which combat pane anyways.  I'm pushing a fix where I just pass in combatPane in the first place, since we already know that.  And I'm going to close this.  Reopen if it shows up again.
