### ISSUE TITLE
Rehydration Issue

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#146]
Loading player Flagrant Noob&Elf&Assassin&1&75@&Melee Attack&Ranged Attack&Assas
sin Stealth&Hidden Shot&Chain Grasp&Ranged Backstab@@&Anatomy@&Basic Healing Pot
ion&Basic Healing Potion&Basic Healing Potion&Antidote&Antidote&Gold: 5@&Crossbo
wFlagrant Noob&Elf&Assassin&1&0@&Melee Attack&Ranged Attack&Melee Attack&Ranged
Attack&Assassin Stealth&Hidden Shot&Chain Grasp&Ranged Backstab@@&Anatomy@&Basic
 Healing Potion&Basic Healing Potion&Basic Healing Potion&Antidote&Antidote&Gold
: 5&Shoes$Potion Effectiveness#3&Scepter$Constitution#1&Gold: 19&Shoes$MP#1&Kata
na&Gold: 18&Gold: 5@&Crossbow
From res\saves\characters\Flagrant Noob_Elf_Assassin.006
Connection made with client on port #32419
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
DEBUG: Basic Healing Potion
DEBUG: Basic Healing Potion
DEBUG: Basic Healing Potion
DEBUG: Antidote
DEBUG: Antidote
DEBUG: Gold: 5
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 32, in server
_loop
    person = TheoryCraft.rehydratePlayer(command.details)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\theorycraft.py", line 150, in
rehydratePlayer
    item = TheoryCraft.rehydrateEquipment(itemName)
  File "e:\Users\Josh\Documents\GitHub\akintu\src\theorycraft.py", line 108, in
rehydrateEquipment
    rValue = item.cloneWithMagicalProperties(0, propertyList)
exceptions.AttributeError: 'NoneType' object has no attribute 'cloneWithMagicalP
roperties'
ClientData lost connection.
ClientDataFactory lost connection.
ServerData lost connection to client on 32419.

**Comment by jabelch** [comment]
Also, the first rehydration seems to work, but with this error

Loading player Flagrant Noob&Elf&Assassin&1&75@&Melee Attack&Ranged Attack&Assa
sin Stealth&Hidden Shot&Chain Grasp&Ranged Backstab@@&Anatomy@&Basic Healing Po
ion&Basic Healing Potion&Basic Healing Potion&Antidote&Antidote&Gold: 5@&Crossb
w
From res\saves\characters\Flagrant Noob_Elf_Assassin.006
Connection made with client on port #32404
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
DEBUG: Basic Healing Potion
DEBUG: Basic Healing Potion
DEBUG: Basic Healing Potion
DEBUG: Antidote
DEBUG: Antidote
DEBUG: Gold: 5
Warning: Attempted to convert from invalid tuple: F .
DEBUG: Basic Healing Potion
DEBUG: Basic Healing Potion
DEBUG: Basic Healing Potion
DEBUG: Antidote
DEBUG: Antidote
DEBUG: Gold: 5
DEBUG: Shoes$Potion Effectiveness#3
DEBUG: Scepter$Constitution#1
DEBUG: Gold: 19
DEBUG: Shoes$MP#1
DEBUG: Katana
DEBUG: Gold: 18
DEBUG: Gold: 5
Saving Character To res\saves\characters\Flagrant Noob_Elf_Assassin.006
ClientData lost connection.
ClientDataFactory lost connection.
ServerData lost connection to client on 32404.

**Comment by jabelch** [comment]
Fixed it (append issue)
