### ISSUE TITLE
Network.py cpickle issue

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#153]
On version bf9b8a3c849821b284880cf3a8a9faaef6bd3ed0 3/12/13

Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 88, in callWi
thLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 73, in callWi
thContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in c
allWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in ca
llWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 1
51, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 215, in doR
ead
    return self._dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 221, in _da
taReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\protocols\basic.py", line 581, in
dataReceived
    why = self.lineReceived(line)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\network.py", line 79, in lineR
eceived
    data = cPickle.loads(zlib.decompress(data))
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
ClientData lost connection.  Reason: Error -5 while decompressing data: incomple
te or truncated stream
ClientDataFactory lost connection.  Reason: Error -5 while decompressing data: i
ncomplete or truncated stream
ServerData lost connection to client on 5984.

**Comment by malikoth** [comment]
Reverted
