### ISSUE TITLE
Server Client Synch failure after levelup

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#154]
After leveling up as a Barbarian and attempting to RUN (SHIFT) I got the error posted below:

Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 148, in
server_loop
    self.person[command.id].ai.start("RUN")
  File "c:\Documents and Settings\Devin\akintu-git\src\ai.py", line 56, in start

```
self.behavior[name]['task'].start(1.0 / self.behavior[name]['frequency'])
```

  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 173, in st
art
    self()
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\ai.py", line 19, in run
    newloc = self.server.person[pid].location.move(direction, 1)
exceptions.AttributeError: 'NoneType' object has no attribute 'person'

**Comment by malikoth** [comment]
Fixed.
