### ISSUE TITLE
Server crash for first player who dies (when both players die)

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#168]
Traceback (most recent call last):
  File "akintu.py", line 54, in main
    hardcore=hardcore)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 113, in __init_
_
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 270, in
 check_turn_end
    for player in [self.server.person[x] for x in self.server.pane[combatPane].p
erson if x in
exceptions.KeyError: ((0, 1), (24, 13), 8)
Loading pane (0, 2)
Unloading pane (0, 0)
Loading pane ((0, 1), (3, 2), 2)
Server error: Attempted to stop non-existent ai function: RUN
Server error: Attempted to stop non-existent ai function: RUN
Poisoned
JAB has status: Poison Fang T=1
Mysterious Adventurer has status: Mystic Shield T=4
<equipment.Weapon object at 0x0A09A830>
<equipment.Armor object at 0x0A09A8B0>
True
Poisoned
JAB has status: Poison Fang T=1
Mysterious Adventurer has status: Mystic Shield T=3
Poisoned
JAB has status: Poison Fang T=1
Mysterious Adventurer has status: Mystic Shield T=2
Poisoned
JAB has status: Poison Fang T=1
Mysterious Adventurer has status: Mystic Shield T=1
Poisoned
JAB has status: Poison Fang T=1
Loading pane (0, 0)
Server error: Attempted to stop non-existent ai function: RUN
Poisoned
Mysterious Adventurer has status: Poison Fang T=1
<equipment.Weapon object at 0x0A09A830>
<equipment.Armor object at 0x0A09A8B0>
True
<equipment.Weapon object at 0x0A09ADB0>
None
False
<equipment.Weapon object at 0x0A09ADB0>
None
False
None
<equipment.Weapon object at 0x0A09ADB0>
None
False
<equipment.Weapon object at 0x0A09ADB0>
None
False
None
<equipment.Weapon object at 0x0A09ADB0>
None
False
<equipment.Weapon object at 0x0A09A830>
<equipment.Armor object at 0x0A09A8B0>
True
<equipment.Weapon object at 0x0A09A830>
<equipment.Armor object at 0x0A09A8B0>
True
<equipment.Weapon object at 0x0A09ADB0>
None
False
<equipment.Weapon object at 0x0A09ADB0>
None
False
None
<equipment.Weapon object at 0x0A09ADB0>
None
False
<equipment.Weapon object at 0x0A09ADB0>
None
False
None
<equipment.Weapon object at 0x0A09ADB0>
None
False
<equipment.Weapon object at 0x0A09A830>
<equipment.Armor object at 0x0A09A8B0>
True
Unloading pane ((0, 1), (3, 2), 2)
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 54, in main
    hardcore=hardcore)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 113, in __init_
_
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 270, in
 check_turn_end
    for player in [self.server.person[x] for x in self.server.pane[combatPane].p
erson if x in
exceptions.KeyError: ((0, 1), (3, 2), 2)
Loading pane (-1, 1)
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 54, in main
    hardcore=hardcore)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 113, in __init_
_
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 270, in
 check_turn_end
    for player in [self.server.person[x] for x in self.server.pane[combatPane].p
erson if x in
exceptions.KeyError: ((0, 1), (3, 2), 2)
Unloading pane (0, 2)

**Comment by jabelch** [comment]
IGNORE THAT CONSOLE OUTPUT: SEE BELOW COMMENT

**Comment by jabelch** [comment]
1337 None {'seed': 'fdsa'} ('Mysterious Adventurer', 'Human', 'Assassin')
Listening for clients...
Connecting to server...
Connection made with client on port #17464
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (-1, 0)
Connection made with client on port #2626
Loading pane ((-1, 0), (23, 9), 8)
Server error: Attempted to stop non-existent ai function: RUN
Server error: Attempted to stop non-existent ai function: RUN
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 132, in game_lo
op
    self.check_queue()
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 278, in check_q
ueue
    'totalHP' : self.pane.person[command.id].totalHP, \
exceptions.KeyError: 167275664
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 54, in main
    hardcore=hardcore)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 113, in __init_
_
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 279, in
 check_turn_end
    self.combatStates[combatPane].turnTimer.cancel()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 88, in can
cel
    raise error.AlreadyCancelled
twisted.internet.error.AlreadyCancelled: Tried to cancel an already-cancelled ev
ent.

**Comment by malikoth** [comment]
I think it's fixed, but I can't duplicate it.  Sorry!  As usual, if you see it again, please reopen this or create a new issue.
