### ISSUE TITLE
Stacktrace when loading games

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#173]
Implemented loading in welcome.py, getting this error every time:

```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1173, in run
    self.mainLoop()
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1182, in mainLoop
    self.runUntilCurrent()
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 805, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 138, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/basepi/src/school/akintu/src/server.py", line 33, in server_loop
    person = TheoryCraft.rehydratePlayer(command.details)
  File "/Users/basepi/src/school/akintu/src/theorycraft.py", line 113, in rehydratePlayer
    bigSplit = longString.split("@")
exceptions.AttributeError: 'NoneType' object has no attribute 'split'
```

Not sure what's going on.  @jabelch @Jzar @BlackVegetable

**Comment by basepi** [comment]
Fixed.  I was passing in the entire path, not just the save name.
