### ISSUE TITLE
Shadow walk client remove error

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#184]
Mysterious Adventurer has status: Howl T=3
Mysterious Adventurer has status: Slightly Smugger T=1
Gray Wolf has status: Weary Bolt T=1
Mysterious Adventurer has status: Howl T=2
Mysterious Adventurer has status: Slightly Smugger T=1
Unloading pane ((0, -1), (8, 7), 6)

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git status
# On branch world
# Changes not staged for commit:
# (use "git add <file>..." to update what will be committed)
# (use "git checkout -- <file>..." to discard changes in working directory)
# 
# modified:   ability.py
# modified:   equippeditems.py
# modified:   passiveability.py
# 

no changes added to commit (use "git add" and/or "git commit -a")

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git add -A

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git commit -m "+Trkstr img hooks; bugfixes"
[world b6ae73b] +Trkstr img hooks; bugfixes
 3 files changed, 18 insertions(+), 8 deletions(-)

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git push origin world
Username for 'https://github.com':
Password for 'https://BlackVegetable@github.com':
Counting objects: 11, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 939 bytes, done.
Total 6 (delta 5), reused 0 (delta 0)
To https://github.com/basepi/akintu.git
   986a316..b6ae73b  world -> world

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ python akintu.py
1337 None {'seed': 'sfadsfda'} ('Mysterious Adventurer', 'Human', 'Dragoon')
Listening for clients...
Connecting to server...
Connection made with client on port #3909
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (1, 0)
Loading pane ((1, 0), (13, 5), 2)
Mysterious Adventurer has status: Chill T=1
Unloading pane ((1, 0), (13, 5), 2)
Loading pane ((1, 0), (5, 15), 6)
Unloading pane ((1, 0), (5, 15), 6)

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ python akintu.py
1337 None {'seed': 'sadf'} ('Mysterious Adventurer', 'Human', 'Dragoon')
Listening for clients...
Connecting to server...
Connection made with client on port #3914
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (0, -1)
Loading pane ((0, -1), (18, 15), 4)
Unloading pane ((0, -1), (18, 15), 4)
Loading pane ((0, -1), (16, 12), 2)
Unloading pane ((0, -1), (16, 12), 2)
Loading pane ((0, -1), (14, 4), 8)
Mysterious Adventurer has status: Bleeding T=3
Mysterious Adventurer has status: Bleeding T=2
Mysterious Adventurer has status: Bleeding T=1
Unloading pane ((0, -1), (14, 4), 8)
Loading pane (1, -1)
Loading pane ((1, -1), (22, 11), 2)
Mysterious Adventurer has status: Bleeding T=3
Mysterious Adventurer has status: Bleeding T=2
Mysterious Adventurer has status: Bleeding T=1
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 29, in s
erver_loop
    self.CS.handle(port, command)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 84
, in handle
    self.check_turn_end(self.server.person[command.id].cPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 28
8, in check_turn_end
    self.end_turn(combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 29
4, in end_turn
    if self.update_dead_people(combatPane) == "CONTINUE_COMBAT":
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 16
2, in update_dead_people
    self.victory_phase(livingPlayers, combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 35
7, in victory_phase
    self.giveVictoryExperience(player, state.deadMonsterList)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 37
6, in giveVictoryExperience
    if player.experience >= player.getExpForNextLevel() and player.level < LEVEL
_MAX:
exceptions.NameError: global name 'LEVEL_MAX' is not defined

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ python akintu.py
1337 None {'seed': 'sadfasfde'} ('Mysterious Adventurer', 'Human', 'Dragoon')
Listening for clients...
Connecting to server...
Connection made with client on port #3919
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Loading pane (0, 0)
Loading pane (0, -1)
Loading pane ((0, -1), (20, 18), 2)
Server error: Attempted to stop non-existent ai function: RUN
Mysterious Adventurer has status: Bleeding T=3
Mysterious Adventurer has status: Bleeding T=2
Mysterious Adventurer has status: Bleeding T=1
Unloading pane ((0, -1), (20, 18), 2)
Loading pane ((0, -1), (26, 14), 2)
Mysterious Adventurer has status: Bleeding T=3
Mysterious Adventurer has status: Bleeding T=3
Mysterious Adventurer has status: Bleeding T=2
Unloading pane ((0, -1), (26, 14), 2)
Loading pane (1, -1)
Loading pane ((1, -1), (6, 11), 4)
Unloading pane ((1, -1), (6, 11), 4)
Loading pane ((1, -1), (10, 17), 4)
Unloading pane ((1, -1), (10, 17), 4)
/-------------------------------------------------------
| Character Name: Mysterious Adventurer
| Level: 2  Experience: 101/250
| Character Class: Dragoon  Race: Human
| HP: 131/131  MP: 0/0  AP: 20/20
| ----------->>> Primary Statistics <<<-----------------
| Strength: 18 (0)  Dexterity: 16 (0)
| Cunning:  13 (0)  Sorcery: 4 (0)
| Piety:    4 (0)  Constitution: 17 (0)
| ----------->>> Secondary Statistics <<<---------------
| Melee Accuracy:    17 (0)  Ranged Accuracy: 16 (0)
| Dodge:             16 (0)  Ranged Dodge: 0 (0)
| Might:             8 (0)  Melee Dodge: 0 (0)
| Spellpower:        4 (0)  Magic Resist: 4 (0)
| Critical Chance:   1% (0)  Critical Magnitude: 0% (0)
| Armor Penetration: 0.75% (0)  Damage Resistance: 0% (0)
| Poison Tolerance:  7 (0)  Poison Rating Bonus: 0 (0)
| Awareness:         13 (0)  Sneak: 3 (0)
| Trap Evade:        14 (0)  Movement Tiles: 2 (0)
| ----------->>> Tertiary Statistics <<<----------------
| Shop Bonus:           1% (0%)  Carrying Capacity: 171 (0)
| Trap Rating Bonus:    0      Trap Damage Bonus: 0%
| Jewlery Bonus:       +0     Potion Bonus Effect: 0%
| Identification:       4 (0)  Gold Find: +0%
| ----------->>> Elemental Resistances <<<--------------
| Arcane Resistance:   0% (0)
| Cold Resistance:     1% (0)
| Divine Resistance:   0% (0)
| Electric Resistance: 0% (0)
| Fire Resistance:     11% (0)
| Poison Resistance:   0% (0)
| Shadow Resistance:   0% (0)
| ----------->>> Elemental Power <<<--------------------
| Arcane Damage Bonus:   0% (0)
| Cold Damage Bonus:     0% (0)
| Divine Damage Bonus:   0% (0)
| Electric Damage Bonus: 0% (0)
| Fire Damage Bonus:     0% (0)
| Poison Damage Bonus:   0% (0)
| Shadow Damage Bonus:   0% (0)
| ----------->>> Active Abilities <<<-------------------
| Level 1: Melee Attack AP: 6 Cooldown: 0
| Level 1: Ranged Attack AP: 6 Cooldown: 0
| Level 1: Expert Notch AP: 7 Cooldown: 1
| Level 1: Brace AP: 2 Cooldown: 0
| Level 1: Jump Attack AP: 15 Cooldown: 2
| Level 1: Mighty Blow AP: 8 Cooldown: 0
| Level 1: Dash AP: 2 Cooldown: 1
| Level 2: Tunnel Vision AP: 10 Cooldown: 5
| ----------->>> Magic Spells <<<-----------------------
| ----------->>> Passive Abilities <<<------------------
| Level 1: Polearm Specialization
| Level 1: Dragon Foe
| Level 2: Fire-Touched
| ----------->>> Traits <<<-----------------------------
| Rank 1 Well-Traveled
-------------------------------------------------------

Loading pane (1, 0)

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git status
# On branch world
# Changes not staged for commit:
# (use "git add <file>..." to update what will be committed)
# (use "git checkout -- <file>..." to discard changes in working directory)
# 
# modified:   game.py
# modified:   servercombat.py
# 

no changes added to commit (use "git add" and/or "git commit -a")

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git add -A

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git commit -m "Added lvlup text."
[world 2787461] Added lvlup text.
 2 files changed, 8 insertions(+), 4 deletions(-)

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git push origin world
Username for 'https://github.com':
Password for 'https://BlackVegetable@github.com':
Counting objects: 9, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 604 bytes, done.
Total 5 (delta 4), reused 0 (delta 0)
To https://github.com/basepi/akintu.git
   b6ae73b..2787461  world -> world

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git pull origin world
Username for 'https://github.com':
Password for 'https://BlackVegetable@github.com':
fatal: Authentication failed

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ git pull origin world
Username for 'https://github.com':
Password for 'https://BlackVegetable@github.com':
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 8), reused 7 (delta 5)
Unpacking objects: 100% (10/10), done.
From https://github.com/basepi/akintu
- branch            world      -> FETCH_HEAD
  Updating 2787461..c4b3d0f
  Fast-forward
  src/game.py    | 29 ++++++++++++++++++++---------
  src/sprites.py |  2 +-
  src/state.py   | 23 +++++++++++++++--------
  3 files changed, 36 insertions(+), 18 deletions(-)

Devin@DEVINSWONKY ~/akintu-git/src (world)
$ python akintu.py
1337 71.195.250.218 None ('Danny the Devito', 'Elf', 'Trickster')
Connecting to server...
Connected to server on IPv4Address(TCP, '71.195.250.218', 1337)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 149, in ga
me_loop
    self.check_queue()
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 282, in ch
eck_queue
    self.pane.person[command.id].removeClientStatus(command.status)
  File "c:\Documents and Settings\Devin\akintu-git\src\person.py", line 267, in
removeClientStatus
    del self._clientStatusView[statusName]
exceptions.KeyError: 'Shadow Walk'

**Comment by BlackVegetable** [comment]
Fixed.  And sorry about that massive unrelated copy-paste.
