### ISSUE TITLE
None is being passed in as one of the item lists in ItemDialog

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#241]
@BlackVegetable, you're currently passing in `None` to the equipment side of the ItemDialog.  If the list is empty, it should be `[]` not `None`.

Traceback:

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1173, in run
    self.mainLoop()
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1182, in mainLoop
    self.runUntilCurrent()
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 805, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 138, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/basepi/src/school/akintu/src/game.py", line 159, in game_loop
    self.handle_events()
  File "/Users/basepi/src/school/akintu/src/game.py", line 556, in handle_events
    self.open_inventory()
  File "/Users/basepi/src/school/akintu/src/game.py", line 725, in open_inventory
    self.screen.show_item_dialog(text, inv, eq, isEquipment, bgcolor='tan', capacity=capacity)
  File "/Users/basepi/src/school/akintu/src/gamescreen.py", line 79, in show_item_dialog
    capacity)
  File "/Users/basepi/src/school/akintu/src/screenutils.py", line 193, in __init__
    self.rightitems = self._generateitems(self.items[1], self.equipment)
  File "/Users/basepi/src/school/akintu/src/screenutils.py", line 362, in _generateitems
    for item in items:
exceptions.TypeError: 'NoneType' object is not iterable
```

**Comment by BlackVegetable** [comment]
This should never happen and a check shouldn't be necessary.  I had a bug elsewhere that was causing it but added the checks anyway.  Regardless, this is fixed now.
