### ISSUE TITLE
Rookie Gladiator Quaff Potion Crash

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#244]
I was playing as a level 1 assassin doing a ranged attack from behind an obstacle when the Gladiator tried to use a Quaff Potion.  It crashed with the following trace:
![GladiatorQuaffPotion](https://f.cloud.github.com/assets/1383245/346943/a346139c-9e7f-11e2-8aec-189dfedac327.png)

Loading pane ((-2, -1), (31, 16), 0, 2)
Server error: Attempted to stop non-existent ai function: run
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\server.py", line 31, in server
_loop
    self.CS.handle(port, command)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 84, in
handle
    self.check_turn_end(self.server.person[command.id].cPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 380, in
 check_turn_end
    self.end_turn(combatPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 389, in
 end_turn
    self.monster_phase(combatPane)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\servercombat.py", line 431, in
 monster_phase
    if not mon.getUsableAbilities(self.server, combatPane, visiblePlayers) and \

  File "E:\Users\Josh\Documents\GitHub\akintu\src\monster.py", line 210, in getU
sableAbilities
    players = self.getPlayersInRange(abil.range, server, combatPane, visiblePlay
ers)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\monster.py", line 277, in getP
layersInRange
    reg("ADD", "SQUARE", self.cLocation.move(7, 1), self.cLocation.move(3, 1))
  File "E:\Users\Josh\Documents\GitHub\akintu\src\location.py", line 128, in mov
e
    direction = dirs[direction]
exceptions.TypeError: 'NoneType' object is not subscriptable

**Comment by BlackVegetable** [comment]
@Jzar do you know why this is happening? one of the locations involved here would land on an impassible tile, but should that really cause a crash?

**Comment by malikoth** [comment]
lol  To answer your question, No.  No, our client should really not crash under any circumstances.  Can I help you with anything else?

**Comment by BlackVegetable** [comment]
I think it I've fixed it.  It was setting a direction to 5 when it was a self ability (for monsters).  This has been fixed.
