### ISSUE TITLE
Key error on animation

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#245]
Just glancing at it, it looks like it can't find an animation sprite for the movement direction 5.

Loading pane ((1, -1), (26, 2), 0, 4)
Server error: Attempted to stop non-existent ai function: run
haha has status: Howl T=4
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 162, in game_lo
op
    self.screen.update()
  File "E:\Users\Josh\Documents\GitHub\akintu\src\gamescreen.py", line 420, in u
pdate
    self.personsgroup.update()
  File "C:\Python27\lib\site-packages\pygame\sprite.py", line 399, in update
    for s in self.sprites(): s.update(*args)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\gamescreen.py", line 913, in u
pdate
    self.image = self.images[foot + (2 \* stealth)][loc.direction]
exceptions.KeyError: 5
ServerData lost connection to client on 60039.
ClientData lost connection.
ClientDataFactory lost connection.

**Comment by BlackVegetable** [comment]
This has been fixed.  Direction 5 should no longer exist.
