### ISSUE TITLE
Error when attempting to level up

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#249]
I tried to level my anarchist up several times.  I believe this was my second or third time from a new character, and this is what I got:

```
1337 None {'seed': 'Correct Horse Battery Staple'} ('Mysterious Adventurer', 'Human', 'Anarchist')
Listening for clients...
Connecting to server...
Connection made with client on port #9343
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
S 9343> Command(type: PERSON, action: CREATE, location: ((0, 0), (16, 10), 0, 2), details: Mysterious Adventurer&Human&Anarchist&1&325&0&False&False@&Melee Attack&Ranged Attack&Face Shot&Brace&Expert Notch&Mighty Blow&Follow Up&Dash@@&Hate Craft@&Basic Healing Potion&Basic Healing Potion&Basic Healing Potion&Antidote@&Hatchet&Medium Shield@@)
Loading pane (0, 0)
Client> Command(type: UPDATE, action: SEED, seed: Correct Horse Battery Staple)
Client> Command(type: UPDATE, action: TURNTIME, turnTime: -1)
Client> Command(type: PERSON, action: CREATE, id: 143386704, details: Mysterious Adventurer&Human&Anarchist&1&325&0&False&False@&Melee Attack&Ranged Attack&Face Shot&Brace&Expert Notch&Mighty Blow&Follow Up&Dash@@&Hate Craft@&Basic Healing Potion&Basic Healing Potion&Basic Healing Potion&Antidote@&Hatchet&Medium Shield@@, location: ((0, 0), (16, 10), 0, 2))
S 9343> Command(type: PERSON, action: REPLACE, player: Mysterious Adventurer&Human&Anarchist&2&325&75&False&False@&Melee Attack&Ranged Attack&Face Shot&Brace&Expert Notch&Mighty Blow&Follow Up&Dash&Trap Worry&Harmless Grin&Tunnel Vision@@&Hate Craft@&Basic Healing Potion&Basic Healing Potion&Basic Healing Potion&Antidote@&Hatchet&Medium Shield@&Trapsmith1@, id: 143386704)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in run
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in mainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in maybeDeferred
    result = f(*args, **kw)
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\game.py", line 163, in game_loop
    self.handle_events()
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\game.py", line 565, in handle_events
    upgradedHero = self.levelup.advance()
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\levelup.py", line 90, in advance
    self._modifyHero()
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\levelup.py", line 111, in _modifyHero
    self.player.passiveAbilities.append(passiveability.PassiveAbility(item.name, self.player))
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\passiveability.py", line 64, in __init__
    self.action(self, self.owner)
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\passiveability.py", line 233, in applyShockAndBurn
    target.baseElectricResistance += 10
exceptions.AttributeError: can't set attribute
```

**Comment by BlackVegetable** [comment]
Yeah, I had a typo turns out.  Thanks!  This fix will be pushed shortly.
