### ISSUE TITLE
New Targeting Crashes On Combat End

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#250]
Devin got this crash when he won combat, I got it when I died:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in mainLoop
    self.runUntilCurrent()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in runUntilCurrent
    call.func(_call.args, *_call.kw)
  File "C:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in **call**
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in maybeDeferred
    result = f(_args, *_kw)
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 162, in game_loop
    self.check_queue()
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 371, in check_queue
    self.update_regions()
  File "E:\Users\Josh\Documents\GitHub\akintu\src\game.py", line 1018, in update_regions
    if l == self.pane.person[self.id].location:
exceptions.KeyError: -1

**Comment by malikoth** [comment]
I believe this is fixed.  As always, reopen if you find it again.
