### ISSUE TITLE
Death in combat (softcore) crash

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#258]
Loading pane ((0, -1), (7, 8), 0, 6)
Server error: Attempted to stop non-existent ai function: run
Starting monster turn.
Starting player turn.
Starting monster turn.
Starting player turn.
Starting monster turn.
Starting player turn.
Starting monster turn.
Starting player turn.
Starting monster turn.
None
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 37, in s
erver_loop
    self.CS.handle(port, command)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 16
2, in handle
    self.prepare_player_turn(command.cPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 45
0, in prepare_player_turn
    self.check_turn_end(combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 41
3, in check_turn_end
    self.end_turn(combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 41
9, in end_turn
    if self.update_dead_people(combatPane) == "CONTINUE_COMBAT":
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 26
3, in update_dead_people
    self.monster_victory(combatPane)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 61
8, in monster_victory
    p = [p for i, p in self.server.person.iteritems() if p.location == combatPan
e][0]
exceptions.IndexError: list index out of range

**Comment by malikoth** [comment]
Fixed.
