### ISSUE TITLE
Error in dual pane dialog

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#260]
```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in run
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in mainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in maybeDeferred
    result = f(*args, **kw)
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\game.py", line 163, in game_loop
    self.handle_events()
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\game.py", line 737, in handle_events
    self.screen.show_dual_pane_dialog(text, left, right, 'gray')
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\gamescreen.py", line 156, in show_dual_pane_dialog
    bgcolor)
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\screenutils.py", line 199, in __init__
    self.leftitems = self._generateitems(self.items[0], self.valuemod[0])
  File "D:\Kyle\Documents\!Documents\Programming\GitHub\akintu\src\screenutils.py", line 408, in _generateitems
    item.type,
exceptions.AttributeError: 'Item' object has no attribute 'type'
```

To see this in action, press CTRL+K in game to activate the keybinding dialog box.

I'm not sure if I'm using your method wrong, or if this is something you need to fix.  Just let me know, thanks!

**Comment by basepi** [comment]
Fixed.

In other news, I'm an idiot.  ;-)
