### ISSUE TITLE
Combat end crash (targeting related?)

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#263]
Starting player turn.
Starting monster turn.
Starting player turn.
Unloading pane ((-1, -1), (22, 18), 0, 8)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 168, in ga
me_loop
    self.check_queue()
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 275, in ch
eck_queue
    self.cycle_targets()
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 1062, in c
ycle_targets
    self.currentTarget = self.panePersonIdList[0]
exceptions.IndexError: list index out of range

**Comment by BlackVegetable** [comment]
Happened when I finished off a monster with a trap-location targeted attack. (Placed a shrapnel trap on him.)

**Comment by BlackVegetable** [comment]
Turns out it happens every time...
