### ISSUE TITLE
Mysterious non-crashing key error

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#265]
Unloading pane ((2, -1), (18, 1), 0, 2)
Unhandled Error
Traceback (most recent call last):
  File "akintu.py", line 53, in main
    hardcore=hardcore)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 132, in __
init__
    reactor.run()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 46
5, in monster_phase
    chars = [self.server.person[x] for x in self.server.pane[combatPane].person]

exceptions.KeyError: ((2, -1), (18, 1), 0, 2)

Seems to happen the last monster dies from a trap.  The game continues just fine though!  This isn't really your issue Jzar, but I'm hoping you can help me figure out what's going on.  Given that it doesn't seem to impact the game, this is a low priority.

**Comment by malikoth** [comment]
Well, it's fixed, even though I couldn't quite figure out the root cause.  Or at least, it appears to be fixed.
