### ISSUE TITLE
Div by zero crash

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#266]
Loading pane (0, 0)
Loading pane (0, -1)
Loading pane (1, -1)
Loading pane ((1, -1), (5, 19), 0, 2)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 203, in
server_loop
    self.CS.startCombat(command.id, person)
  File "c:\Documents and Settings\Devin\akintu-git\src\servercombat.py", line 35
5, in startCombat
    self.server.load_pane(combatPane, monsterId)
  File "c:\Documents and Settings\Devin\akintu-git\src\server.py", line 442, in
load_pane
    self.pane[pane] = self.pane[pane.pane].get_combat_pane(pane, self.person[pid
], numPlayers)
  File "c:\Documents and Settings\Devin\akintu-git\src\pane.py", line 407, in ge
t_combat_pane
    return CombatPane(self, focus_tile, monster, num_players)
  File "c:\Documents and Settings\Devin\akintu-git\src\pane.py", line 602, in __
init__
    self.traps_region("SUB", "SQUARE", loc, loc)
  File "c:\Documents and Settings\Devin\akintu-git\src\region.py", line 70, in _
_call__
    self.locations -= getattr(self, shape.lower())(*details)
  File "c:\Documents and Settings\Devin\akintu-git\src\region.py", line 159, in
square
    for y in loc1.line_to(Location(loc1.abs_x, loc2.abs_y)):
  File "c:\Documents and Settings\Devin\akintu-git\src\location.py", line 190, i
n line_to
    locs.append(Location(self.abs_x + int(round(float(x) / dist \* distx)),
exceptions.ZeroDivisionError: float division by zero

**Comment by malikoth** [comment]
Fixed
