### ISSUE TITLE
Weird startup crash

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#268]
Devin@DEVINSWONKY ~/akintu-git/src (world)
$ python akintu.py
1337 None {'seed': 'Correct Horse Battery Staple'} ('Mysterious Adventurer', 'Hu
man', 'Druid')
Listening for clients...
Connecting to server...
Connection made with client on port #2485
Connected to server on IPv4Address(TCP, '127.0.0.1', 1337)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 159, in se
tup_game
    LoopingCall(self.game_loop).start(1.0 / DESIRED_FPS)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 173, in st
art
    self()
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 170, in ga
me_loop
    self.handle_events()
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 552, in ha
ndle_events
    self.move_person(keystate.direction("MOVEMENT"))
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 976, in mo
ve_person
    if self.pane.person[self.id].anim:
exceptions.AttributeError: 'NoneType' object has no attribute 'person'
Loading pane (0, 0)

**Comment by BlackVegetable** [comment]
I think this happened because I interrupted the loading screen with an ALT-TAB or something.  So this may be a very low priority.

**Comment by BlackVegetable** [comment]
Yeah this happens only when you interrupt the GUI loading by selecting a different window (in Windows) at an inopportune time.
