### ISSUE TITLE
Softcore death crash?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#276]
I'm not even sure who to assign this to. @basepi, @jabelch 

Starting player turn.
Starting monster turn.
Loading pane (0, 0)
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1173, in r
un
    self.mainLoop()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 1182, in m
ainLoop
    self.runUntilCurrent()
  File "c:\Python27\lib\site-packages\twisted\internet\base.py", line 805, in ru
nUntilCurrent
    call.func(_call.args, *_call.kw)
  File "c:\Python27\lib\site-packages\twisted\internet\task.py", line 218, in __
call__
    d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted\internet\defer.py", line 138, in m
aybeDeferred
    result = f(_args, *_kw)
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 182, in ga
me_loop
    self.check_queue()
  File "c:\Documents and Settings\Devin\akintu-git\src\game.py", line 252, in ch
eck_queue
    self.screen.add_person(command.id, persondict)
  File "c:\Documents and Settings\Devin\akintu-git\src\gamescreen.py", line 431,
 in add_person
    self.persons[personid] = PersonSprite(statsdict)
  File "c:\Documents and Settings\Devin\akintu-git\src\gamescreen.py", line 980,
 in **init**
    self.image = self.images[foot + (2 \* stealth)][loc.direction]
exceptions.AttributeError: 'NoneType' object has no attribute 'direction'

**Comment by BlackVegetable** [comment]
This happens every time this world is loaded now. Hmm, not sure how to upload a file but not to the repository.  I guess I can put it in @basepi 's dropbox and have him host it somewhere privately.

**Comment by basepi** [comment]
Just FYI, if you put triple backticks (or graves or whatever you want to call them) around something in GitHub, it treats it as a code block.

```
like this
```

It's easier to read terminal stuff that way.  =)  Looking into this now.

**Comment by basepi** [comment]
So I don't think this is me.  `None` is being passed in for the `'location'` part of the statsdict for add_person.  Find where the None comes from, and you find the problem!  =D

**Comment by jabelch** [comment]
I'm going to need a little more information to replicate this.  Can you provide specifics on who you were playing as, what seed you were using, and which monster you were fighting?  Can you replicate this crash?

**Comment by jabelch** [comment]
I'm going to take a look at this save file later...
http://files.basepi.net/misc/013_2013-04-27_1018.akinw
